# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'pinterest_Test' do
pod 'PinterestSDK', :git => 'https://github.com/pinterest/ios-pdk.git'
end

